### ISSUE TITLE
Add Context Menu or Swipe-able Menu to List/Grid Items

### ISSUE THREAD

**Issue by DavidTPate** [antew/RedditInPictures#102]
We currently allow a user to open, upvote, and downvote a particular post from the list view. The grid view just allows them to open. 

Ideally we would provide a couple higher usage functions either via a context menu (long press) or a swipe-able menu (accessible via swipe or long press). I think we should hold off on this for now with the grid, once we move to a Staggered Grid through with a more card-like look and feel we would be able to implement this similar to how Pocket does it on the tablet where long pressing reveals a small menu within the same area. So, either the card would grow slightly in height or we would reduce the image height as we display the menu.

**Comment by DavidTPate** [comment]
Thinking the options would be View, Save, Open in Browser, Share, and Report Image

**Comment by antew** [comment]
I like it. I tried out the list in Pocket and I think it is a cool effect, but it is a bit harder to use. I was caught a couple of times by making a small swipe down and accidentally closing the menu. 

With the swipe you get immediate feedback because the view moves with you, but with long press you have a consistent delay and it feels slower to me.

**Comment by DavidTPate** [comment]
Yeah, I'm thinking that we would have both the ability to swipe and long press.

**Comment by DavidTPate** [comment]
Stubbed this out initially with 46b7b00

**Comment by DavidTPate** [comment]
@antew I'm thinking that for the Grid view we should wait on this functionality until we add in a Staggered Grid View as it will all be thrown away at that point. I'm not sure how it would look either with the current implementation. The best I can come up with is that we would animate the image flipping around to reveal the menu behind it.
