### ISSUE TITLE
ImageDetailActivity Leak

### ISSUE THREAD

**Issue by DavidTPate** [antew/RedditInPictures#152]
Somewhere along the line ImageDetailActivity is being leaked and more than 1 instance is open.

```
com.antew.redditinpictures.pro E/StrictMode﹕ class com.antew.redditinpictures.library.ui.ImageDetailActivity; instances=2; limit=1
    android.os.StrictMode$InstanceCountViolation: class com.antew.redditinpictures.library.ui.ImageDetailActivity; instances=2; limit=1
            at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
```

**Comment by antew** [comment]
I tried to reproduce this today when I was working on #159, but it looks like it has been fixed.  Can you see if you can still reproduce it?

**Comment by DavidTPate** [comment]
I haven't been able to reproduce this with the latest code. I'm thinking it was related to RedditFragmentActivity being leaked.

**Comment by antew** [comment]
Closing for now then, will reopen if we can reproduce it.

**Comment by DavidTPate** [comment]
I was able to reproduce this by changing orientation on ImageDetailActivity. Reopening.

**Comment by DavidTPate** [comment]
Pretty certain this is taken care of. The culprit looked to be the onPageLoaded listener for the webview.
