### ISSUE TITLE
Implement Sliding Navigation for Subreddit List

### ISSUE THREAD

**Issue by DavidTPate** [antew/RedditInPictures#2]
The current method for displaying subreddits doesn't work well with long lists or for managing the subreddits. Instead we want to move the list to slide out navigation and provide some ease of use features. Below is an example from Reddit is Fun. Something similar would be ideal, where you have the ability to filter the current list (and those that are loaded and searched for are saved in Shared Preferences) as well as search for new subreddits. 

![image](https://f.cloud.github.com/assets/2223120/1955545/66909cca-81ea-11e3-9222-36ab36887dbe.png)

Additionally, simplifying mass editing of subreddits as well as creating combinations of subreddits needs to be introduced. Sorting would be an ideal feature as well which could be sorted either based on largest usage at the top or alphabetically. This setting should be saved based on preference. So if in Session 1 the user select alphabetical sorting, in Session 2 it should still be alphabetical.

**Comment by antew** [comment]
Started this with 25a026b4976a0973f638ac1ce84eacfbcf7f29fa

**Comment by antew** [comment]
Selecting a subreddit from the menu now displays it with deee8c06e13fcc8cfde908973a07eb7221aac4f0
