### ISSUE TITLE
Move Age Selection From Action Bar to Tabs

### ISSUE THREAD

**Issue by DavidTPate** [antew/RedditInPictures#45]

**Comment by antew** [comment]
I disagree on this one, it will take space away from the area for images, and I don't think the feature is used often enough to justify it. I could see making it a dropdown in the drawer, but I don't think it is bad having it as an action icon.

**Comment by DavidTPate** [comment]
Yeah, what you are saying makes sense. I'd be interested in seeing what else we can do with it.

**Comment by DavidTPate** [comment]
Closing this one, for the current release I think we should keep it like it currently is.
