### ISSUE TITLE
Expanding view in subreddit menu closes when scrolled off screen and back

### ISSUE THREAD

**Issue by antew** [antew/RedditInPictures#94]
Open the subreddit menu, expand a subreddit, scroll it off screen and back on screen. The expanding view will be closed.

**Comment by DavidTPate** [comment]
Makes sense, the view is recycled so the menu is closed. I don't think this is bad behavior and code to make this work would be more of a hack. In my opinion the intent of the user would be that if they are scrolling away then they are either done with the menu or no longer care. I don't see a need to make it stateful in some way.
